### PR TITLE
New Feature: add LightBulb RRect

### PR DESCRIPTION
**Pull request by dbbd59**
Hi! awesome work with this package!
I added the possibility to change the shape of the bulb into a rectangle.

### CODE REVIEW

**Comment by dbbd59** [comment]
Screenshot 2019-05-22 at 15 36 20

**Comment by dbbd59** [comment]
Hi! I added the possibility to click on the children widgets to proceed with the tutorial.

**Comment by alexandranb** [comment]
Hi,
Great job!
How can I download this?
This would really help me out.

Thank you

**Comment by dbbd59** [comment]
Thank you! 
https://github.com/dbbd59/tutorial_coach_mark
this is the repository with the updated example.

to use it add this to your pubspec.yml.
```
tutorial_coach_mark:
    git:
      url: https://github.com/dbbd59/tutorial_coach_mark.git
```

**Comment by RafaelBarbosatec** [comment]
sorry for the delay. I'll be testing and I'll accept the request :-)
good job!

**Pull request merged**
